FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
 && pip install --prefer-binary numpy \
 && pip install --no-cache-dir -r requirements.txt

RUN pip install watchdog

# This assumes app.py will be mounted from host at runtime
EXPOSE 7860

CMD ["watchmedo", "auto-restart", "--directory=.", "--pattern=app.py", "--recursive", "--", "python", "app.py"]
